Nt/Areas/Admin/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Nt.Models;
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace Nt.Areas.Admin.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            }
        }

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateRoleModel model)
        {
          

            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new ApplicationRole
                {
                    Name = model.Name,
                    Description = model.Description
                });
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Что-то пошло не так");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                return View(new EditRoleModel { Id = role.Id, Name = role.Name, Description = role.Description });
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> Edit(EditRoleModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationRole role = await RoleManager.FindByIdAsync(model.Id);
                if (role != null)
                {
                    role.Description = model.Description;
                    role.Name = model.Name;
                    IdentityResult result = await RoleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Что-то пошло не так");
                    }
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
    }
}

Nt/Areas/Admin/Views/Roles/Create.cshtml
@model Nt.Models.CreateRoleModel

<h2>Добавление роли</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, "")
        <p>Название:  @Html.EditorFor(model => model.Name)</p>
        <p>Описание: @Html.EditorFor(model => model.Description)</p>
        <p><input type="submit" value="Добавить" /></p>
    </div>
}

Nt/Areas/Admin/Views/Roles/Edit.cshtml
@model Nt.Models.EditRoleModel

<h2>Редактирование роли</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, "")
        @Html.HiddenFor(model => model.Id)
        <p>Название:  @Html.EditorFor(model => model.Name)</p>
        <p>Описание: @Html.EditorFor(model => model.Description)</p>
        <p><input type="submit" value="Изменить" /></p>
    </div>
}

Nt/Areas/Admin/Views/Roles/Index.cshtml
@model IEnumerable<Nt.Models.ApplicationRole>

@{
    ViewBag.Title = "Роли";
}

<h2>Роли</h2>
@Html.ActionLink("Создать роль", "Create", "Roles", new { area = "Admin" }, new { @class = "navbar-brand" })
<table class="table">
    <tr>
        <th>Название</th>
        <th>Описание</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>